#!/bin/sh

ABdir=$(find /var/mobile/Containers/Bundle/Application/ -name "AlienBlue.app")

if [[ $1 == remove && -d "$ABdir" ]]; then
	echo "Removing Ponymotes from $ABdir/Subreddits.bundle/"
	rm -rf $ABdir/Subreddits.bundle/{mylittlepony,MLPLounge} 2>/dev/null
fi

exit 0